### ISSUE TITLE
sorry to piggyback off of this post. i tried the reset instructions here in MacOS terminal and everything seems to go right. But when I go to hoobs.local or 192.168.1.67 (my box's IP), i get the Chrome error page that reads, "This site can't be reached" Any thoughts to get to some sort of resolution?

### ISSUE THREAD

**Issue by Armandl23** [hoobs-org/HOOBS#1228]
sorry to piggyback off of this post. i tried the reset instructions here in MacOS terminal and everything seems to go right. But when I go to hoobs.local or 192.168.1.67 (my box's IP), i get the Chrome error page that reads, "This site can't be reached" Any thoughts to get to some sort of resolution?

_Originally posted by @runningfool20 in https://github.com/hoobs-org/HOOBS/issues/912#issuecomment-761728182_

**Comment by Armandl23** [comment]
I have exactly the same issue 
My Hoobs in a Box is stuck and unreachable 
I applied the reset procedure in "Factory Reset Hoobs in a Box and then actually get it working with Apple HomeKit #912" but my Hoobs remains unreachable

**Comment by runningfool20** [comment]
The only way I got my to work again, was to take out the micro sd card and completely flash it and start all over. I followed the instructions here and got everything going again — https://hoobs.org/step-by-step-guide-downloadhoobs/

mine has been working well ever since. I’ve generally avoided issues by only installing certified plugins.

**Comment by Armandl23** [comment]
Thanks that worked for me too
