### ISSUE TITLE
Hoob.local no longer accessible

### ISSUE THREAD

**Issue by tomallan84** [hoobs-org/HOOBS#1310]
I have purchased Hoobs out of the box. I successfully had it connected via ethernet to my network, had upgraded it, and was trying to get the RING plugin setup. 

Suddenly, the Hoobs is no longer accessible via hoobs.local. I've tried turning it off and on, no good. Nothing else has changed other than me trying to tinker with the ring plugin settings. Every time I go to Hoobs.local I get "This site can't be reached" 

Any help appreciated.

**Comment by ColinScattergood** [comment]
Same issue here. Not sure how long its been an issue because its been a bit since I tried to access it. But I can't for the life of me get it to load. Seemed to load this morning but it was spotty...Tried updating to 3.3.6 thinking it'd fix it, but I think it made it significantly worse.

**Comment by tomallan84** [comment]
Why did this get closed?

**Comment by mkellsy** [comment]
Had many stale issues that needed to be cleaned up.
Re opening.

**Comment by mkellsy** [comment]
Are you able to ping the box
open the Terminal or Command Prompt
and type this command

```
ping hoobs.local
```

What does it return?

**Comment by takeitothegrill** [comment]
After update of Hoobs, I also cannot access hoobs.local

As per @mkellsy request, can still ping box through Terminal.

Return is:
64 bytes from 192.168.1.111: icmp_seq=4 ttl=64 time=14.940 ms

**Comment by mkellsy** [comment]
The ping tells us that the device is up.

You will need to access the terminal
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Once you are connected, run this command
```
sudo systemctl status hoobs
```
Or if you are on 4.0
```
sudo systemctl status hoobsd
```

**Comment by tomallan84** [comment]
> Are you able to ping the box
> open the Terminal or Command Prompt
> and type this command
> 
> ```
> ping hoobs.local
> ```
> 
> What does it return?

Sorry for the delay in replying, I was away on a trip. 

I have just tried pinging using terminal, and this was the response: 
ping: cannot resolve hoobs.local: Unknown host

**Comment by hmart316** [comment]
I'm also having the same issue. Performed an update this morning and can login via SSH. 

after running "sudo systemctl status hoobs" I get the following. All bridge devices are working fine however I'm not sure what else I should do to manage the bridge via GUI again. Any help would be appreciated.  :)

● hoobs.service - HOOBS
   Loaded: loaded (/etc/systemd/system/hoobs.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-26 05:21:42 MDT; 18min ago
 Main PID: 29134 (node)
    Tasks: 22 (limit: 2062)
   CGroup: /system.slice/hoobs.service
           ├─29134 hoobs
           └─29145 hoobs

Jul 26 05:21:52 hoobs hoobs[29134]: [HOOBS 55ED@Outdoor Plug 2@Outdoor Plug 2@Volts] Characteristic not in required or optional characterist
Jul 26 05:21:52 hoobs hoobs[29134]: [HOOBS 55ED@Outdoor Plug 2@Outdoor Plug 2@Consumption] Characteristic not in required or optional charac
Jul 26 05:21:55 hoobs hoobs[29134]: [myQ] myQ API: Successfully connected to the myQ API.
Jul 26 05:21:55 hoobs hoobs[29134]: [Ring] Found the following locations:
Jul 26 05:21:55 hoobs hoobs[29134]: [Ring]   locationId: **[removed for privacy]** - Hammond
Jul 26 05:21:55 hoobs hoobs[29134]: [Ring] Configuring 2 cameras and 3 devices for location "Hammond" - locationId: **[removed for privacy]**
Jul 26 05:21:56 hoobs hoobs[29134]: [Nest] initing thermostat "Nest Thermostat": deviceId: **[removed for privacy]** structureId: 4abde260-678f-11e4-
Jul 26 05:21:56 hoobs hoobs[29134]: [Nest] initing home_away_sensor "Home Occupied": deviceId: **[removed for privacy]** structur
Jul 26 05:21:59 hoobs hoobs[29134]: [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: **[removed for privacy]**, gateway: G
Jul 26 05:21:59 hoobs hoobs[29134]: [myQ] myQ API: Discovered device family gateway: Garage Door [Chamberlain WiFi GDO AC] (serial number: G

**Comment by Vanouxx** [comment]
Same Problem here.... :-(

I yesterday wanted to update to Hoobs 4. Now, I can't get a response from the box, it just glows red und that's it......

no response with the ping :-(

**Comment by BobbySlope** [comment]
contact us via email info@hoobs.com, we can schedule a remote session
