### ISSUE TITLE
Vera Plugin Fails to Install

### ISSUE THREAD

**Issue by Nasscar** [hoobs-org/HOOBS#1360]
**Description**

**Version**
Please include the version of HOOBS you are using.
4.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE7/10/2021, 9:06:02 AMVera BridgeWARNINGNo plugins installed.
7/10/2021, 9:06:02 AMVera BridgeBridge is running on port 52826.
7/10/2021, 9:11:38 AMVera BridgeConfiguration change
7/10/2021, 9:11:46 AMVera BridgeWARNINGNo plugins installed.
7/10/2021, 9:11:46 AMVera BridgeLoading 1 platforms...
7/10/2021, 9:11:46 AMVera BridgeBridge is running on port 52826.
7/10/2021, 9:28:45 AMVera BridgeERRORError: ENOENT: no such file or directory, open '/var/lib/hoobs/verabridge/cache'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at Function.saveJson (/usr/src/services/paths.ts:66:18)
    at Cache.save (/usr/src/services/cache.ts:106:19)
    at process.teardown (/usr/src/main.ts:51:54)
    at process.emit (events.js:375:28)
    at process.emit (/usr/lib/hoobsd/node_modules/source-map-support/source-map-support.js:495:21)
7/10/2021, 9:29:19 AMVera BridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0```
```

**Additional context**

**Comment by mkellsy** [comment]
What version of node are you running
```
node -v
```

**Comment by Nasscar** [comment]
v14.17.2

**Comment by mkellsy** [comment]
OK, wired.

Try removing the bridge and trying again.
Go to the **Bridges** screen, select **Vera Bridge**
Click the **Remove** button and confirm.

Then go back to the **Plugin Library** and try installing the plugin again.

**Comment by Nasscar** [comment]
I have tried that method several times with the same error result. 

Note: 

I have also tried the 3 other vera plugs as well.

**Comment by mkellsy** [comment]
The first plugin intentionally crashes the bridge if the IP isn't set. HOOBS will attempt to restart the bridge. I made a change if the bridge stops right away it will not try to restart it.

This is fixed in the next release.

1. You will first need to remove the **Vera Bridge**.
2. Then reboot. **Menu** -> **Hub Settings** click on **Reboot**
3. After a reboot, click **Check for Updates**. If you see an update for HOOBSD **4.0.80** then continue. Otherwise you may need to wait.
4. Then you can install the **Vera** plugin. The bridge will stop right away.
5. Edit the config **Config Screen** -> **Advanced** then go to the **Vera Bridge** tab.
6. Add your **"veraIP"** setting.
7. Go to **Bridges Screen** and select the **Vera Bridge**
8. Click the **Start** button
