### ISSUE TITLE
Custom Install Can't Access

### ISSUE THREAD

**Issue by Dakvar** [hoobs-org/HOOBS#1373]
**Description**
I freshly installed Hoobs on a Pi 3B but I can't reach hoobs.local to set it up.

**Version**
4.0.31.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
macOS BigSur

I am able to reach homebridge, when I flash it on the Pi instead of hoobs. But since Homebridge doesn't properly work (I can't connect it to the Home App) I really want to use Hoobs. But like I said I can't even reach hoobs.local :( Can anyone help?

**Comment by mkellsy** [comment]
I noticed you marked that you did a custom install. Can you elaborate?
* Did you download our image and flash it to an SD Card?
* Did you install this on an existing Raspberry Pi OS (Raspbian)?

Sometimes depending on your operating system, the mDNS hoobs.local address might not be available. There are things you can do.
* If you do have mDNS installed (Avahi) you can access your device with http://[hostname].local where [hostname] is the name you assigned to your device. If you use one of our images, the hostname is *hoobs*, hence http://hoobs.local.
* If you don't have mDNS installed, and your client computer supports Kerbos, like Windows, you can access your device at http://[hostname]. Again [hostname] is the name of your device, like http://hoobs.
* If you don't have access to either, you can use the IP address as Bobby stated. It would be something like this http://192.168.x.x.

Also note, if you installed using the `sudo apt install hoobs` command, this automatically sets this up on port 80. If you have any other software using this port, it will fail. Because HOOBS sandboxes bridges, it is best to use a dedicated device for HOOBS. If you do have something else running on port 80, you will need to change your configuration.

First reset the software.
```
sudo hbs system reset
```

Then re-initilize
```
sudo hbs install
```
During this command you will be asked which port you want to run on, select something other then 80.
