### ISSUE TITLE
Advanced Plugin Install Interface

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#142]
To provide a working solution with all plugins and for all user groups, it would may be necessary to provide advanced settings for a plugin installation as used in the HM App. 

These settings should may include the option to allow a sudo/root installation and a selection of tags/versions. (Global flag optional?)

Maybe we should discuss it in team.

**Comment by mkellsy** [comment]
install forked-Plugin from issue #129

**Comment by mkellsy** [comment]
is there a way to install forked Plugins from the UI ?

**Comment by mkellsy** [comment]
What plugin are you looking at?

**Comment by mkellsy** [comment]
Forked could mean many things.
1. In Node you can fork a process. Some plugins do this.
2. On GitHub you can fork a project.

I am assuming the latter. In this case, you need to rename the package in package.json. then publish to NPM to install from the UI.

**Comment by mkellsy** [comment]
> From @rpolenthon

Michael, I think it wouldn’t be that bad if we add a option to install forked plugins from GitHub directly. This would be a good advanced feature. I think Bobby already opened an issue for a standard git integration, so it shouldn’t be a big thing to allow installations from git

**Comment by mkellsy** [comment]
More
https://github.com/hoobs-org/HOOBS/issues/129

**Comment by mkellsy** [comment]
It is not recommended to install plugins globally. HOOBS contains all plugins within it's own node_modules. The only thing this prevents is creating symlinks in /usr/local/bin (which is a good thing).

To access these side loaded binaries, they will have to be called from the ~/.hoobs/node_modules folder. Plus this behavior will prevent the plugin from being certified.

To install plugins from GitHub, there is a terminal. Users can cd ~/.hoobs/ and npm install [url]. This will install the plugin locally.

Also since plugins are managed by HOOBS, a manually installed plugin will not load. The user must add it to the plugins: [] variable in the config.json. Also they will need to create a platform: [] entry with the plugin_map JSON.

Because of this, it is not recommended to install manually. Yes installing plugins is very easy from the UI. However, to make this easy, there is a ton of stuff to do. Therefore making it harder to install plugins from the terminal.

I think we have a great thing working here, adding something abstract like this will make the UI harder to understand. If I come think of an elegant way of doing this, I will consider it. But for now, I am marking this issue Wont Fix.
