### ISSUE TITLE
Hoobs version 4.0.71

### ISSUE THREAD

**Issue by Micky187** [hoobs-org/HOOBS#1422]
**Description**
Im finding my Hoobs version contains many bugs i.e. many of the screens get stuck on the loading screen and never load, like settings or plugin config. The rest seems ok. I downloaded the latest image of Hoobs (file name 4.0.31) however once installed, the GUI reads its 4.0.71 - but I have not seen any release notes available for this version on GitHub - could this be a version that is yet to be released that I somehow downloaded?

**Version**
4.0.71
**Did you upgrade**
No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No

**What device are you using?**
Please let us know the device you are running HOOBS on.
 Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 
Hoobs image running on Pi 4B

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
Can't access config via terminal, but Even with no config issue occurs

```
POST CONFIG HERE
```

**Post your log**
log appears empty in GUI
```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
the version you are on is ok. HOOBS automatically updates while installing.
Please provide more info eg. Screenshots Log etc. to elaborate what exactly isnt working.

**Comment by mkellsy** [comment]
HOOBS has multiple components.

- HOOBSD, this is the server component that runs on the Pi
- GUI, this is the web interface
- CLI, this is the command line tools
- Desktop, this is the app that runs on your computer

The version on the release in our main repo is just the Pi image build. We do this so we can fix issues in each component without having to upgrade the other parts. Each component has its own version. We display the server version on your dashboard.

You can view all changes from the commit logs.
https://github.com/hoobs-org/hoobsd/commits/main
https://github.com/hoobs-org/gui/commits/main
https://github.com/hoobs-org/cli/commits/main
https://github.com/hoobs-org/desktop/commits/main

I am working on a tool to auto parse our commit logs to create a change log. Currently it is too much for me to handle to write the code and also a change log, both are full time jobs. Until I complete this, we have to use the commit logs.

As for the network issues you are seeing in the plugin screen. This is a known issue and it has 2 parts.

1. I have a wait call that is causing too many calls.
2. The plugin's dependencies can take some time to download.

The first part is fixed in GUI and Desktop version currently in Edge testing. GUI 4.0.80, Desktop 4.0.50

The second part is out of my control. Most plugins don't have large dependencies. Others like Weather Plus have deps that download large databases. In the case of Weather Plus, it downloads a VERY LARGE geo coding library.

**Comment by Micky187** [comment]
Thank you both very much for your very detailed responses :)
