### ISSUE TITLE
If I wanted to install hoobs, pivpn, and pi hole, on one pi

### ISSUE THREAD

**Issue by lacedup** [hoobs-org/HOOBS#145]
How would I go about this? Is a 3b+ enough?

**Comment by mkellsy** [comment]
This is not a simple answer. There are many factors.

HOOBS runs on ports 8080, 51826, 51827 and 51828 if you **don't** run the hoobs-init script. However you will need to configure HOOBS to run as a service manually.

If you do run the **hoobs-init** script, this will install NGINX and run HOOBS from port 80. This will conflict with Pi Hole. However you can re-configure NGINX to run on a different port. You will need to edit the /etc/nginx/conf.d/hoobs.conf file and change the listen ports from 80 to something like 90.

HOOBS, will use more resources than PiVPN and Pi Hole, because it communicates with HAP, and runs plugins based on what you have in your house. PiVPN and Pi Hole uses more network and memory. So essentially you could run all 3 on a single Pi, but you will need to test this on your own.

If you want to attach cameras to HOOBS, I would not run anything else on the Pi. In-fact video transcoding uses a ton of resources, and we can only get live video with an 8 second lag time. In this case we recommend a more powerful solution like a Pi 4B or a Tinker Board S (we are testing this currently). Some users are using a Mac Mini for HOOBS, so they have more power for live video.
