### ISSUE TITLE
System Monitoring Push Alerts

### ISSUE THREAD

**Issue by lacedup** [hoobs-org/HOOBS#154]
Maybe a script along side hoobs that checks the homebridge status.

**Comment by mkellsy** [comment]
In version 3 HOOBS runs in 3 parts.

1. The API
2. Homebridge
3. The Interface

Homebridge is controlled by the API and is monitored. Since the API doesn't have plugins is it more stable. So essentially HOOBS monitors its self.

So when you bring up the interface, it is up regardless if Homebridge is down, it tells you if Homebridge is running.

**Comment by mkellsy** [comment]
After digging into your Reddit post, I think you are looking for a push alert. I am updating the issue title.

**Comment by mkellsy** [comment]
The dashboard shows the current status of the Homebridge service.
