### ISSUE TITLE
Expose HOOBS weather data in Homekit

### ISSUE THREAD

**Issue by jqnatividad** [hoobs-org/HOOBS#1589]
**Describe the solution you'd like**
HOOBS already has the data, why not expose it to Homekit?  Especially with the [DarkSky API going dark  in 2022](https://blog.darksky.net/).

**Describe alternatives you've considered**
I used to use https://github.com/naofireblade/homebridge-weather-plus with Dark Sky, but it's not HOOBS certified, and I don't want to add another bridge.

**Additional context**
It'd be another additional enticement/feature to add to HOOBS differentiators!

**Comment by mkellsy** [comment]
I have been thinking about this for a while.

The system works like this.
There is a Hub and that Hub spawns Bridges (Homebridge). The bridges communicate with HomeKit.

I don't want to connect the Hub to Homekit because it breaks this architecture. However...

I have decided to make a plugin that exposes all controls to HomeKit including switches to turn on and off bridges and the weather too.
