### ISSUE TITLE
Hoobs ssh login issue for ssh

### ISSUE THREAD

**Issue by EarmarkedHuman** [hoobs-org/HOOBS#1668]
When I logged into the hoobs account through terminal on my Hoobs Box I changed the password from
Hoobsadmin but now it won't let me in with the new password. I was very careful to make sure the password typed was correct and have it saved in my password vault so I know I typed it correctly. How do I gain access to this account again without having to do a full reset? It was a real pain to get some of my plugins to work so I REALLY don't want to have to redo it all. I did do a backup before I changed the password.

**Comment by askovi** [comment]
You cannot recover the terminal password if you lost it. Check your capslock and make sure it's typed correctly then press enter.

If you have a backup you can simply reflash the HOOBS img then restore your backup from the hub settings (assuming it's a full backup from the same place). You won't lose anything including Homekit connection. 

If you made individual bridge backups instead of a full backup then you must restore each one individually.

**Comment by mkellsy** [comment]
If you still have access to the UI go to the config screen -> hub and click the reset terminal button.

**Comment by EarmarkedHuman** [comment]
> If you still have access to the UI go to the config screen -> hub and click the reset terminal button.

That worked a charm! Thanks! Good to know that exists. Now I'm running into the same issue after the reset. It appears that no matter what password I set to replace hoobsadmin, the terminal will ask me for the login and when I enter the new password it just cycles back to the login id prompt.

**Comment by EarmarkedHuman** [comment]
okay, rebooting it twice seems to have fixed the login issue. When in doubt, reboot, reboot, reboot 🤣

**Comment by mkellsy** [comment]
When the terminal asks to change the password, it will ask you to login once you change it.
