### ISSUE TITLE
Looking for old versions of Hoobs

### ISSUE THREAD

**Issue by TDT1969** [hoobs-org/HOOBS#1669]
Hi, I have a RPi 2B that I've been running HOOBS on.  I had to start over (long story) and I need to reinstall.  I've purchased and can re-download HOOBS from my account, but only the latest version.  Where can I get the last/best version that ran on a 2B?

**Comment by askovi** [comment]
You can download the old HOOBS 3 for armv6 here: https://github.com/hoobs-org/hoobs-build/releases/download/v3.2.10/HOOBS-3.2.10-ARM6.zip

However it's highly recommended that you either upgrade your Pi or get a HOOBS Box in order to benefit of HOOBS 4. See here what's new in HOOBS 4: https://support.hoobs.org/docs/60ddef1128162f9d13da96af

**Comment by TDT1969** [comment]
Thanks!
