### ISSUE TITLE
Again, no updates for plugins

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1675]
Since 8 days: LG ThinQ ver. 1.2.11
Stil on 1.2.10

**Comment by bwp91** [comment]
On the plugins section go to the bridge of the plugin and go to the versions page. Click the download icon on the row which says “latest” on the right. This will download the latest version of the plugin. Just make sure to install it to the bridge where the plugin is currently installed rather than a new bridge

**Comment by Christian-CFP** [comment]
Thank you!
