### ISSUE TITLE
Update Not possible

### ISSUE THREAD

**Issue by alphac84** [hoobs-org/HOOBS#1749]
Hi,

My hoobs installation shows version 4.0.110. When I search for updates nothing is found but I read that there is a more current version available. 

How can I upgrade to the new version?

Regards,
Jörg

**Comment by bwp91** [comment]
Take a look at this:

https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535

**Comment by macnut123** [comment]
I have the same issue. I cannot login from the terminal, as suggested, and it will not update from 4.0.110 from the app or the website on my iPad or MacBook.
I’ve tried resetting my hoobs box and it still will not update.
Is it a hardware issue with the box?
Al

**Comment by mkellsy** [comment]
You can try re-flashing
https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9e060dcf29f5e39f03278

**Comment by macnut123** [comment]
OK, that worked perfectly! Thank you!
When I updated to version 4 I remember I could not access the server with my browser, so I unplugged the unit and restarted it. While it restarted and I could access via my browser, I have not been able to update the software since. That must have caused the problem. I refreshed to the latest system and now Simplisafe works great once again.
Happy new year!
Al

**Comment by mikegull** [comment]
https://support.hoobs.org/topics/resetting-re-flashing/what-is-the-fix-command
