### ISSUE TITLE
How to install different versions of plugins?

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#186]
Hello,

I want to install a beta version for the Homematic plugin.
If I install it via terminal with sudo npm install -g homebridge-homematic@0.1.2 the installation works but the plugin does't load in Hoobs.
Which is the proper way for installing plugins manually?

**Comment by mkellsy** [comment]
First of all I am assuming that you are running HOOBS 3.0.0 beta. These instructions will not work for HOOBS 2.1.1.

HOOBS doesn't use plugins installed globally. We do this because installing random code globally is very, very, very insecure. We not only want to make Homebridge easy, we want to make it secure. This is a major difference from Homebridge.

Installing the latest, stable plugins via the interface is very easy. However, to do this manually there is more involved. HOOBS uses a plugin white list. We do this for security, and for instances, where multiple instances of HOOBS is running on the same device, but doesn't need to load all of the plugins.

Before doing this, you need to uninstall the plugin globally.
1. `sudo npm uninstall -g homebridge-homematic`

Here's how to install manually.
1. Log in as the user running HOOBS (HOOBS runs in user mode)
2. `cd ~/.hoobs/` (You need to be in the directory where HOOBS runs)
3. `npm install homebridge-homematic@0.1.2` (Don't use a -g)
4. `nano ~/.hoobs/etc/config.json`
5. Add "homebridge-homematic" to the "plugins": [] array.

```
{
    ...
    "plugins": [
        ...
        "homebridge-homematic"
    ]
    ...
}
```

6. When you add the platform config JSON. Add the `plugin_map` to the platform config.

```
{
    ...
    "platforms": [
        ....
        {
            "platform": "Homematic",
            ...
            "plugin_map": {
                "plugin_name": "homebridge-homematic"
            }
        }
    ]
}
```

The `plugin_map.plugin_name` needs to the the name of the plugin folder, not the platform name.

**Comment by Bladestar2105** [comment]
Thank you!
