### ISSUE TITLE
Certified Plugins Conflict with Non Certified Versions

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#190]
There needs to be a detection of installed plugins whether certified or not in order to now allow a conflicting plugin with same name to be installed (eg. If I have Ring plugin installed and I want to install the HOOBS Certified Ring, prompt to confirm uninstall of Ring first). Try to keep the config however since it will be the same.

**Comment by mkellsy** [comment]
I made it work so if a plugin fails it sends an error.

NEXT STEP
After an install before populating the plugins array load installed plugins and search for plugins with the same alias. If found, uninstall the non hoobs versions.

Since I have the plugin name, I should be able to find all platforms and accessories that are mapped to this plugin and update the platform or accessory variables.

I will also need to modify Homebridge to not fail on platform configs that have no plugins.

**Comment by mkellsy** [comment]
Certified plugins now completely replace non certified versions in the search. If you try to install the non certified version, the system will install the certified version anyway.

Also if you install a certified plugin it will first remove the non certified version first.

Done in 3.0.0-beta.68
