### ISSUE TITLE
If HOOBS is stopped when saving advanced config file it does not start

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#192]
It normally restarts if it's already on when making config file changes but if it's stopped because it crashed before it does not try to start by itself when saving. It must be manually started from menu. Also starting it manually doesn't seem to work unless reloading the page.

**Comment by mkellsy** [comment]
This is by design. If HB is stopped for any reason it requires the user to start it.

Imagine this if a user stops HB to configure it, and is in the middle of configuring and saves changes. Doesn't want HB to start. This would anger the user. For the most part, users will not be starting or stopping. We do restart on save, but not a start.

This is by design.

**Comment by askovi** [comment]
Since this behavior differs from v2.1.1 it needs to be made more obvious.

**Comment by mkellsy** [comment]
We can add a save and start button if HB is stopped.

**Comment by askovi** [comment]
That works.

**Comment by mkellsy** [comment]
I just made the save button start the HB service.

Done in 3.0.0-beta.68
