### ISSUE TITLE
I get permission denied when installing plugins or uninstalling

### ISSUE THREAD

**Issue by dmatchx** [hoobs-org/HOOBS#215]
I just upgraded to hoobs v3 but now I can’t uninstall or install plugins, not sure if I missed anything but couldn’t find any open or closed issue about.
![39915517-4D1E-44FC-9EE0-3C4084EBFD16](https://user-images.githubusercontent.com/51839567/67149753-45f48f80-f27d-11e9-90c5-f80f8625a746.jpeg)
I get the error when installing from GUI or terminal.

**Comment by dmatchx** [comment]
I fix all user folder user owner and now I can add plugins with no problem.

**Comment by stephenmd** [comment]
how did you solve it mate? keep running into this issue every time there's an update

**Comment by mkellsy** [comment]
Run this
npm cache clean --force

Or
sudo npm cache clean --force

Or
rm -fR ~/.npm

**Comment by stephenmd** [comment]
thank you! so initially you'd just install the plugins by not including sudo?

**Comment by mkellsy** [comment]
No, Homebridge plugins typically install globally. This requires sudo. HOOBS installs per user, without sudo.

Sometimes when running npm install with sudo, it can put cached plugins in the cache with root permissions. So when you try to use the user's cache, they have no permission because they are not root.

HOOBS uses NPM the way it is supposed to.
