### ISSUE TITLE
Catch Nested Platform and Accessory Config Errors

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#267]
**Description**
HOOBS is crashed, No Response on all accessories in the Home app and this spams in logs:
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
However it shows as running in the dashboard and the top right menu:
![image](https://user-images.githubusercontent.com/3981552/69935347-911bd800-14a2-11ea-8b21-a93404c06cef.png)

**Version**
HOOBS3 beta80

**Additional context**
The way I crashed it is by entering the wrong stuff in the configuration screen for a platform. I added the Platforms[ ] array in addition to the platform object, mimicking what a user might do when copy/pasting from npm. 

HOOBS should not crash for misconfiguring any plugin. 
If HOOBS does manage to crash, it should showcase appropriately in the dashboard.

**Comment by mkellsy** [comment]
127.0.0.1:51826 is the HAP server.

**Comment by mkellsy** [comment]
I am moving this to the HIC project.

**Comment by mkellsy** [comment]
I found the issue. If you copy and paste from the plugin's readme, it can cause errors. Most plugin devs, don't speak non programming talk, so users will not understand that the `"platforms": [ ... ]` part of the example is not to be copied, and it is used as a reference.

I expanded our validation logic that automatically corrects this case. It will also correct users doing this `[{ ... }]`.

This if fixed in 3.0.1.
