### ISSUE TITLE
Ring Plugin not Hoobs certified after 3.1.1 upgrade?

### ISSUE THREAD

**Issue by JazzerAlto** [hoobs-org/HOOBS#295]
**Description**
I had the ring plug in prior to the 3.1.1 upgrade.  It doesn't recognize it was Hoobs certified.  I get an option to install via the plug in search even though its the same plug in.  Shouldn't Hoobs recognize it is certified?

**Expected behavoir**
Should be certified 

**Plugin name**
Ring

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

2.1.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY29JD",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": ""
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba",
            "model": "e5",
            "blid": "",
            "robotpwd": ":",
            "ipaddress": "192.168.100.205",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30
        }
    ],
    "platforms": [
        {
            "email": "",
            "password": "",
            "hideLightGroups": false,
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "platform": "Ring"
        }
    ]
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
They are 2 separate plugins. If you had the Ring plugin installed prior to migrating to HOOBS 3, it also migrated your regular Ring plugin in order to keep it running. HOOBS 3 supports both versions. The certified version is tested by the HOOBS team upon every new update and the update is released to the HOOBS certified version when deemed fully compatible with the HOOBS system as well as ensuring no security flaws. This means new features might sometimes be delayed on the certified version.
If you'd like to use the HOOBS certified version, start by uninstalling the current Ring plugin, then installing the HOOBS certified version from the plugins section.
