### ISSUE TITLE
Need to Test Installing Ring Plugin

### ISSUE THREAD

**Issue by srenne7** [hoobs-org/HOOBS#307]
I'm unable to install plugins in 3.1.1. I click install and then it loads and redirects to the plugin page where it says "No plugins installed." Below is the log:

[12/9/2019, 9:08:11 PM] HOOBS listning on port 8080.
[Homebridge] [12/9/2019, 9:08:20 PM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [12/9/2019, 9:08:20 PM] ---
[Homebridge] [12/9/2019, 9:08:21 PM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/9/2019, 9:08:22 PM] Loading 0 platforms...
[Homebridge] [12/9/2019, 9:08:22 PM] Loading 0 accessories...
[Homebridge] X-HM://0023ISYWY1FG6
[Homebridge] [12/9/2019, 9:08:23 PM] Service is running on port 51826.
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/23/8b'
npm
 ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
[12/9/2019, 9:09:40 PM] Installed "@hoobs/ring" package.

Thank you in advance!

**Comment by BobbySlope** [comment]
please provide us more info.
which plugin you tried to install? @hoobs/ring?

**Comment by srenne7** [comment]
Sure! This particular instance was with @hoobs/ring, but I've also tried homebridge-dummy and neither worked.

**Comment by BobbySlope** [comment]
Can u provide is outputs from log after failed install?

**Comment by srenne7** [comment]
[12/10/2019, 9:36:21 AM] Installed "@hoobs/ring" package.

**Comment by srenne7** [comment]
But the "Installed Plugins" tab still displays "No plugins are installed"

**Comment by mkellsy** [comment]
From adavison007

**Description**
If you configure the ring features via the UI some work, some don't the one I know definitely does not work is Motion.... so If I set "Hide Motion Sensors" to false, they do not appear... If I leave it blank and delete that line in the JSON, they do appear.

The Ring Cameras, motion sensors and light switches also do not appear as accessories in hoobs

**Expected behavoir**
Motion tiles should appear

Devices should appear in hoobs ui

**Plugin name**
Homebridge-Ring @hoobs

**Please report the issue to the plugin developer**
Done

**Version**
3.1.1
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X
<img width="807" alt="Untitled 2" src="https://user-images.githubusercontent.com/47482260/70850734-97885780-1e85-11ea-8d6d-74c283c271c3.png">
 ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
This is fixed in 3.1.4
