### ISSUE TITLE
Unable to install homebridge-automation-bluetooth-presence ?

### ISSUE THREAD

**Issue by GDeb59** [hoobs-org/HOOBS#345]
**Description**
Hi,

I had some trackers Nut Mini 3 so I tried to install this module homebridge-automation-bluetooth-presence in order to manage who is at home.

It failed to install with this module : bluetooth-hci-socket

Another question I have a RPI3 B+. Is it better to use a BT 4 dongle or native bluetooth in RPI3 ?

Thanks for help.

PS : I'm using Hoobs (Homebridge out of the box) 3.1.1

**Expected behavoir**
I expect installation of this plugin ok.

**Plugin name**
homebridge-automation-bluetooth-presence

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [] Custom Install 

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
You can easy reproduct issue with an image of latest Hoobs version.
I tried with/without a dongle USB BLE 4 to check with native BLE.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
@GDeb59 I have some bad news. This plugin uses a package called noble. It has some issues and is not installing everything it needs. There is an issue open on this already.
https://github.com/noble/noble/issues/918

I tried to install this plugin on many different versions, 12.13.1, 10.17.0, 10.16.3 and 10.15.2. Was unable to build the bluetooth-hci-socket package. This could be due to my VM's I tested this on. I will test on a RPI 3+ and 4 when I can.

I have a feeling that this plugin doesn't work on Node 12.13.1, we are downgrading the default with HOOBS to 10.17.0. So I will test this on 10.17.0.

**Comment by AndreasLueck** [comment]
Still open! All Hoobs BT Plugins don't run because of that noble version which is stuck. But there are plugins that are using node-mi-flora / @abandonware/noble in the background with the same package dependencies. @abandonware/noble is a version of noble that has support for Node 10+. Hope we can use Hoobs featured plugins like Mi Flora soon...
