### ISSUE TITLE
Cannot find Module: homebridge-smartthings-v2

### ISSUE THREAD

**Issue by flynhawaiian** [hoobs-org/HOOBS#368]
**Description**
Not able to view plugin settings in the plugin configuration panel, or be able to upgrade it without using the terminal.  The plugin operates perfect otherwise.

Log
<Cannot find module 'homebridge-smartthings-v2'
Unable to determine plugin type for "homebridge-smartthings-v2">

**Expected behavoir**
Show the module settings and ability to upgrade it via hoobs plugin panel 

**Plugin name**
homebridge-smartthings-v2

**Version**
3.1.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Comment by mkellsy** [comment]
This is because the homebridge-smartthings-v2 doesn't use the standard index.js file in the root. So when I load it to find the plugin type, it can't find the code.

To fix this I am loading the pjson.main directive and loading the src/ sub directory.

Now I need to figure out why the platofrm.schema.json file is not being loaded.
