### ISSUE TITLE
No Ethernet activity

### ISSUE THREAD

**Issue by brainguynyc** [hoobs-org/HOOBS#461]
My hoobs in a box is getting power but shows no Ethernet activity. Does not show as a connected device on my router and of course I have no control over any dependents. Help please

**Comment by BobbySlope** [comment]
Please contact us via info@hoobs.org
Please send us your order confirmation, and we can schedule a remote session to help you, or send you an replacement.

**Comment by askovi** [comment]
Please make sure you plugged the ethernet cable prior to plugging in the power cable, otherwise it will default to Wi-Fi. Look for green and amber light activity on the left and right side of the ethernet port. 

If there’s no light activity after a few seconds, the SD card might be corrupted. If you’re a HOOBS Box customer, please send an email to info@hoobs.org with your order number and a free replacement will be shipped to you asap.

**Comment by brainguynyc** [comment]
askovi, I sent an email to the address you gave but haven't received a confirmation. How should I proceed?
Thanks.

**Comment by brainguynyc** [comment]
BobbySlope, I did.

**Comment by askovi** [comment]
Check your email for an SD card replacement order. It will ship out today.

**Comment by brainguynyc** [comment]
I have HOOBS in a box for beginners. I can simply open the case and replace the microSD card?

**Comment by askovi** [comment]
Correct. There are 4 screws on the bottom of the HOOBS Box. You can open it takes the SD card our and put in the new one.

**Comment by brainguynyc** [comment]
Ok. Thanks!
