### ISSUE TITLE
Node not upgrading with 3.1.27

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#559]
**Description**
The Node-Version was not updated so it stays on 12.14.1.

**Version**
3.1.27

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.1.26

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Debian 10

**List your plugins**
I think this is not important for this issue.

**Post your config**
I think this is not important for this issue.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
I think this is not important for this issue.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
node 12.4.1 is stable.
If you want a newer version, you can upgrade it like this:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 12.16.2 `

**Comment by kbardai** [comment]
same, my hoobs says 3.1.27 but node is still at 12.4.1 instead of 12.16.2 as it says in the release notes for 3.1.27 (https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.27).

Don't know if it makes a difference but I have to update hoobs using the following command thru terminal, update it does not work through the gui (installed on ubuntu server x86):

`sudo npm_config_user=root npm install -g --unsafe-perms @hoobs/hoobs`

**Comment by Bladestar2105** [comment]
> node 12.4.1 is stable.
> If you want a newer version, you can upgrade it like this:
> `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 12.16.2`

Thank you, this worked for me 🙂👍
