### ISSUE TITLE
How can I update node?

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#585]
How can I update node?
Still on 12.14.1 and this does not mach the HUE plugin.

`WARN notsup Unsupported engine for homebridge-hue@0.11.64: wanted: {"BSB001":"1.16.0","BSB002":"1.37.0","deCONZ":"2.5.75","homebridge":"~1.0.0","node":"^12.16.2"} (current: {"node":"12.14.1","npm":"6.14.4"}) 2.5.2020, 00:26:37 npm WARN notsup Not compatible with your version of node/npm: homebridge-hue@0.11.64 npm WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.14.1","npm":"6.14.4"}) npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1`

**Comment by askovi** [comment]
That’s just a warning not an error. If you want to update you can use this command in terminal: 
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin —node 12.16.2`

**Comment by Christian-CFP** [comment]
Hi, yes, I updated to 12.16.3 now. And I'll try.
HUE Plugin does not work with this "warning" and I cound not update. The HUE plugin disappears and I cant add it back. So I had to go back to 0.11.63.

I'll test now. Thx.

**Comment by Christian-CFP** [comment]
While update:
`+ homebridge-hue@0.11.64
added 45 packages from 23 contributors in 5.865s
2.5.2020, 09:38:29 
32 packages are looking for funding
  run `npm fund` for details`

And HUE Plugin disappears from hoobs... :( Cant install it again.

**Comment by askovi** [comment]
`sudo nano /home/hoobs/.hoobs/etc/config.json`

Check the plugins [ ] array and make sure “homebridge-hue” is listed. If it isn’t then add it yourself and save with ctrl+s then exit with ctrl + x. Then reboot from the top right menu.

**Comment by Christian-CFP** [comment]
@askovi You are awesome. That fixed it. Thank you!

**Comment by Christian-CFP** [comment]
@askovi When did you plan to upgrade node in hoobs?
Hue asks for 12.18.4

The upper code does not work to upgrade...

**Comment by Christian-CFP** [comment]
Wow, no one response... Great Job! tx :(

**Comment by BobbySlope** [comment]
we are working on an major update that will include node

**Comment by sTsJoch** [comment]
I like that you made HOOBS in a Box because i have no Idea how to handle a Rhaspberry PI. Now I need an update of my Node Version. I have NO clue what that is but the new Version of the "Homebridge Fritz Platform" need s a Node Version >=12.18.3 . The current version on my HOOBS is 12.14.1

How can i update it? When will your major update come?

**Comment by Christian-CFP** [comment]
Run this two commands from terminal. Connect via ssh. 

`sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm  @hoobs/hoobs `

**Comment by sTsJoch** [comment]
Hello Christian. Thank you for trying to help me. But I bought HOOBS in a Box because I don’t know how to handle a Rhaspberry PI. I don’t know how to connect my PC to the PI via ssh and  what terminal software I have to use.

 

 

 

 

Von: Christian-CFP <notifications@github.com> 
Gesendet: Montag, 30. November 2020 21:26
An: hoobs-org/HOOBS <HOOBS@noreply.github.com>
Cc: sTsJoch <github@net-affairs.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hoobs-org/HOOBS] How can I update node? (#585)

 

Run this two commands from terminal. Connect via ssh.

sudo npm uninstall -g @hoobs/hoobs sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by Christian-CFP** [comment]
Englisch/German?

**Comment by sTsJoch** [comment]
Ich spreche deutsch

 

Von: Christian-CFP <notifications@github.com> 
Gesendet: Montag, 30. November 2020 21:37
An: hoobs-org/HOOBS <HOOBS@noreply.github.com>
Cc: sTsJoch <github@net-affairs.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hoobs-org/HOOBS] How can I update node? (#585)

 

Englisch/German?

**Comment by Christian-CFP** [comment]
Ok, du nutzt Windows?
Rufe die Eingabeaufforderung auf und tippe folgenden Befehl ein:

`ssh hoobs@hoobs.local `

Das Passwort lautet hoobsadmin

Dann tippst du die oberen Befehle ein. Einen nach dem anderen.

**Comment by sTsJoch** [comment]
Ok - this seemed to work. Now i restarted HOOBS. I can only see the orange starting screen with the animated white line under your HOOBS Logo. Is it normal that the first start needs long after an update? its about 10 minutes now and nothing happens

**Comment by Christian-CFP** [comment]
> Ok - this seemed to work. Now i restarted HOOBS. I can only see the orange starting screen with the animated white line under your HOOBS Logo. Is it normal that the first start needs long after an update? its about 10 minutes now and nothing happens

Hatte einen Dreher in der Reihenfolge der Befehle. In dem Post hier drüber habe ich eine korrekte Reihenfolge drin.

**Comment by sTsJoch** [comment]
Ok - i did it exactly the way you described and the Node is now updated. Thank you very much !!!
