### ISSUE TITLE
HOOBS Docker Template

### ISSUE THREAD

**Issue by e8link** [hoobs-org/HOOBS#68]
I’d give this a try but I run almost everything in Docker on unraid.  How about a docker template on dockerhub?

**Comment by BobbySlope** [comment]
We were using docker in version 1 and 1.1. But we changed back to raspian and systemd because all tutorials our there are based on this. Users got confused when they not can apply standard tutorials and establish standard system connection. 

We may think about it when we solved everything config editing related and ssh etc is no longer needed. But this wont be in version 3 for now

**Comment by mkellsy** [comment]
This is similar to the SD card img. There are things we need to do with networking, but that's about it.
