### ISSUE TITLE
How to install drivers?

### ISSUE THREAD

**Issue by Flaunkerton2395** [hoobs-org/HOOBS#777]
Hi everyone!

I am a new user and I know how to install plugins, but i'm completely lost on how to install drivers or plugins from GitHub urls. Can anyone help me out? Thank you!

**Comment by askovi** [comment]
If you want to install anything outside of HOOBS, you can use the terminal from the top right menu. Or you can also connect via ssh using user: hoobs and password hoobsadmin

Installing plugins from github urls is not supported from the UI. You could do it via the terminal as well but it requires you to do all the plugin setup yourself. You have to install it in hoobs' node_modules folder then add it to the package.json and you must manually edit the config.json file via the terminal to add it to the plugins array so that it shows up in the UI. Then you must also add the config block manually in the platforms or accessories array.
