### ISSUE TITLE
Entire HOOBS config deleted!

### ISSUE THREAD

**Issue by chemicalsam** [hoobs-org/HOOBS#852]
My HOOBS would not boot after a power failure, so I looked here to see if anyone had a solution. I was still able to SSH into HOOBS in Terminal and it was reachable.

I follow the HOOBS team advice that they posted to someone else;

The issue is NGINX is running. You have 2 options.
> 
> Disable NGINX
> 

```
sudo systemctl disable nginx
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
sudo reboot
```

After doing this however, my ENTIRE hoobs setup was deleted. All my plugins and settings and accessories were completely wiped. All 35 accessories added were gone. Everything. Gone.

**Comment by askovi** [comment]
Those commands don't delete anything, they just disable the nginx service. 
Check your etc folder for the config file and config backups: `ls ~/.hoobs/etc`

Also, you can always just restore from a local backup, if you made one, by going to settings -> restore

**Comment by chemicalsam** [comment]
```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ ls ~/.hoobs/etc
access.json                config.json.1583458661257
accessories                config.json.1583459671011
config.json                dashboard.json
config.json.1583203822543  homebridge-hubitat.log.0
config.json.1583278162509  homebridge-hubitat.log.0.gz
config.json.1583278296240  homebridge-hubitat.log.1.gz
config.json.1583278762770  homebridge-hubitat.log.2.gz
config.json.1583278891141  layout.json
config.json.1583279290544  persist
config.json.1583458539238
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 

```

**Comment by askovi** [comment]
first check the contents of the main config.json file, is it empty?

`cat ~/.hoobs/etc/config.json`

If it contains the proper config for your plugins that you had installed, you might have started hoobs as root which starts a separate instance which is why you're not seeing the plugins. 

If that file has the basic config that HOOBS comes with without the plugins, then you have some autobackups in that folder, the latest one being `config.json.1583459671011`

Check its contents `cat ~/.hoobs/etc/config.json.1583459671011`
If it contains the right config, then you can replace the main file with it like this:
`sudo rm -rf ~/.hoobs/etc/config.json`
`sudo mv ~/.hoobs/etc/config.json.1583459671011 ~/.hoobs/etc/config.json`

Then you can go in the HOOBS UI and just install the plugins you had and the config will already be there. 

You might have to do a Reset Connection from the top right menu -> Help - > Reset Connection
Then scan the new QR code on the dashboard to add the bridge again to Homekit.

**Comment by chemicalsam** [comment]
Trying the first two methods both just show 
`    "accessories": [],`
With a blank accessories number, so how do I know if its the right backup or not?

**Comment by askovi** [comment]
Look in the "platforms": [] array. Most plugins register a platform not an accessory.

**Comment by chemicalsam** [comment]
> Look in the "platforms": [] array. Most plugins register a platform not an accessory.

`"platforms": [ ],`

**Comment by chemicalsam** [comment]
> Look in the "platforms": [] array. Most plugins register a platform not an accessory.

**Comment by chemicalsam** [comment]
> `sudo rm -rf ~/.hoobs/etc/config.json`
> `sudo mv ~/.hoobs/etc/config.json.1583459671011 ~/.hoobs/etc/config.json`
```
 011 ~/.hoobs/etc/config.jsonbs/etc $ sudo mv ~/.hoobs/etc/config.json.15834596710
mv: cannot stat '/home/hoobs/.hoobs/etc/config.json.1583459671011': No such file or directory
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
```

I did this command and nothing happened again, this is very frustrating.

**Comment by mkellsy** [comment]
When copying files via the terminal the file needs to be there.

These commands should get you there.
First you need to make sure you are in the config folder
```
cd ~/.hoobs/etc
```

Then look at the files using the ls command
```
ls
```

Look at the files. The config backup files are labeled config.json.[TIMESTAMP]. From you post above, config.json.1583458661257 is the file you need. So copy (not move) that file as you main config.json file.
```
cp ./config.json.1583458661257 ./config.json
```

That's all you need. The important part is to copy a file that is already there.
