### ISSUE TITLE
New hoops

### ISSUE THREAD

**Issue by pbregieira** [hoobs-org/HOOBS#976]
**Description**
Today I received the device, after updating and installing a plugin for my fibaro 2, everything was working correctly. Until a power failure, the device does not restart and is not detectable on the network, making it impossible to access it by ssh. What should I do???

**Version**
Hoobs 3.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Big Sur

**List your plugins**
Fibaro hc2

**Post your config**
it is not possible to access via ssh

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
it is not possible to access via ssh

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
That issue seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the latest img file from the GitHub releases of this repository.
