### ISSUE TITLE
Hoobs Device

### ISSUE THREAD

**Issue by hasnaink786** [hoobs-org/HOOBS#984]
I own a standalone Hoobs device.

I installed a plug-in for Soma blinds and ran the 2 terminal commands (I think about enabling the bluetooth stacks). Now the system won't start.
I get:
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'
when trying to reach Hoobs.local

I also tried ssh via Terminal on my Mac, and I get: 
kex_exchange_identification: read: Connection reset by peer

What can I do?

Thanks

**Comment by askovi** [comment]
Something must have gone wrong because that error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by hasnaink786** [comment]
Thanks. I did update. I did do the above successfully. now the Hoobs Box doesn't boot up I think at all. Trying to reach it via hoobs.local on my browser. no response. re-flashed the SD card and still nothing.
The unit shows power red light at the USB cable, and the ethernet cable also shows the orange and green activity light flickering away.

**Comment by askovi** [comment]
Check your router's admin page or app for the local ip address given to HOOBS and try to reach it like this: http://192.168.x.x (replace with actual ip). The old ip is probably cached by the browser for hoobs.local

**Comment by hasnaink786** [comment]
Hi. It does not show up on the list of connected devices on the router's page. if I unplug it from the ethernet cable, the wifi Hoobs access point shows up, and I add it to my wifi, but then I can't access it via the new IP once it is on the wifi network. I tried reflashing the sd card in case something was corrupt, but the same issue.

**Comment by hasnaink786** [comment]
Ok. Restarted again, and all is working. Now. Thanks.
